// Code generated by goserdegen v0.1.0. DO NOT EDIT.

package safeshapes

import (
	"github.com/tochemey/goserde/codec"
)

var _ = codec.UvarintSize // keep import if unused

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *All) Size() int {
	s := 0
	s += 1
	s += 1
	s += 2
	s += 4
	s += 8
	s += 4
	s += 8
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	s += codec.UvarintSize(uint64(len(r.Blob)))
	s += len(r.Blob)
	s += codec.UvarintSize(uint64(len(r.Tags)))
	for _, e1 := range r.Tags {
		s += codec.UvarintSize(uint64(len(e1))) + len(e1)
	}
	s += codec.UvarintSize(uint64(len(r.Nums)))
	s += 4 * len(r.Nums)
	s += codec.UvarintSize(uint64(len(r.Scores)))
	for e2, e3 := range r.Scores {
		_ = e2
		_ = e3
		s += codec.UvarintSize(uint64(len(e2))) + len(e2)
		s += 4
	}
	s += 1
	if r.Ptr != nil {
		s += 4
	}
	s += (&r.Inner).Size()
	s += 1
	if r.Nested != nil {
		s += (&(*r.Nested)).Size()
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *All) Marshal(b []byte) int {
	i := 0
	if r.Flag {
		b[i] = 1
	} else {
		b[i] = 0
	}
	i++
	b[i] = byte(r.N8)
	i++
	codec.PutU16(b[i:], uint16(r.N16))
	i += 2
	codec.PutU32(b[i:], uint32(r.N32))
	i += 4
	codec.PutU64(b[i:], uint64(r.N64))
	i += 8
	codec.PutU32(b[i:], codec.F32bits(r.F32))
	i += 4
	codec.PutU64(b[i:], codec.F64bits(r.F64))
	i += 8
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	i += codec.PutUvarint(b[i:], uint64(len(r.Blob)))
	i += copy(b[i:], r.Blob)
	i += codec.PutUvarint(b[i:], uint64(len(r.Tags)))
	for _, e4 := range r.Tags {
		i += codec.PutUvarint(b[i:], uint64(len(e4)))
		i += copy(b[i:], codec.S2B(e4))
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Nums)))
	for _, e5 := range r.Nums {
		codec.PutU32(b[i:], uint32(e5))
		i += 4
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Scores)))
	for e6, e7 := range r.Scores {
		i += codec.PutUvarint(b[i:], uint64(len(e6)))
		i += copy(b[i:], codec.S2B(e6))
		codec.PutU32(b[i:], uint32(e7))
		i += 4
	}
	if r.Ptr != nil {
		b[i] = 1
		i++
		codec.PutU32(b[i:], uint32((*r.Ptr)))
		i += 4
	} else {
		b[i] = 0
		i++
	}
	i += (&r.Inner).Marshal(b[i:])
	if r.Nested != nil {
		b[i] = 1
		i++
		i += (&(*r.Nested)).Marshal(b[i:])
	} else {
		b[i] = 0
		i++
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *All) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 1 {
		return i, codec.ErrShortBuffer
	}
	r.Flag = b[i] != 0
	i++
	if len(b)-i < 1 {
		return i, codec.ErrShortBuffer
	}
	r.N8 = int8(b[i])
	i++
	if len(b)-i < 2 {
		return i, codec.ErrShortBuffer
	}
	r.N16 = uint16(codec.U16(b[i:]))
	i += 2
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.N32 = int32(codec.U32(b[i:]))
	i += 4
	if len(b)-i < 8 {
		return i, codec.ErrShortBuffer
	}
	r.N64 = uint64(codec.U64(b[i:]))
	i += 8
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.F32 = codec.Bitsf32(codec.U32(b[i:]))
	i += 4
	if len(b)-i < 8 {
		return i, codec.ErrShortBuffer
	}
	r.F64 = codec.Bitsf64(codec.U64(b[i:]))
	i += 8
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if uint64(len(b)-i) < nn {
		return i, codec.ErrShortBuffer
	}
	r.Name = string(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if nn == 0 {
		r.Blob = nil
	} else {
		if uint64(len(b)-i) < nn {
			return i, codec.ErrShortBuffer
		}
		r.Blob = append(r.Blob[:0], b[i:i+int(nn)]...)
		i += int(nn)
	}
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if nn == 0 {
		r.Tags = nil
	} else {
		if uint64(len(b)-i) < nn {
			return i, codec.ErrShortBuffer
		}
		if cap(r.Tags) >= int(nn) {
			r.Tags = r.Tags[:nn]
		} else {
			r.Tags = make([]string, nn)
		}
		for j8 := range r.Tags {
			nn, cc = codec.Uvarint(b[i:])
			if cc <= 0 {
				return i, codec.ErrShortBuffer
			}
			i += cc
			if uint64(len(b)-i) < nn {
				return i, codec.ErrShortBuffer
			}
			r.Tags[j8] = string(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if nn == 0 {
		r.Nums = nil
	} else {
		if uint64(len(b)-i) < nn {
			return i, codec.ErrShortBuffer
		}
		if cap(r.Nums) >= int(nn) {
			r.Nums = r.Nums[:nn]
		} else {
			r.Nums = make([]int32, nn)
		}
		for j9 := range r.Nums {
			if len(b)-i < 4 {
				return i, codec.ErrShortBuffer
			}
			r.Nums[j9] = int32(codec.U32(b[i:]))
			i += 4
		}
	}
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if nn == 0 {
		r.Scores = nil
	} else {
		if uint64(len(b)-i) < nn {
			return i, codec.ErrShortBuffer
		}
		j10 := nn
		if r.Scores != nil {
			clear(r.Scores)
		} else {
			r.Scores = make(map[string]int32, j10)
		}
		for j11 := uint64(0); j11 < j10; j11++ {
			var j12 string
			var j13 int32
			nn, cc = codec.Uvarint(b[i:])
			if cc <= 0 {
				return i, codec.ErrShortBuffer
			}
			i += cc
			if uint64(len(b)-i) < nn {
				return i, codec.ErrShortBuffer
			}
			j12 = string(b[i : i+int(nn)])
			i += int(nn)
			if len(b)-i < 4 {
				return i, codec.ErrShortBuffer
			}
			j13 = int32(codec.U32(b[i:]))
			i += 4
			r.Scores[j12] = j13
		}
	}
	if len(b)-i < 1 {
		return i, codec.ErrShortBuffer
	}
	if b[i] != 0 {
		i++
		var j14 uint32
		if len(b)-i < 4 {
			return i, codec.ErrShortBuffer
		}
		j14 = uint32(codec.U32(b[i:]))
		i += 4
		r.Ptr = &j14
	} else {
		i++
		r.Ptr = nil
	}
	{
		nnn, err := (&r.Inner).Unmarshal(b[i:])
		if err != nil {
			return i, err
		}
		i += nnn
	}
	if len(b)-i < 1 {
		return i, codec.ErrShortBuffer
	}
	if b[i] != 0 {
		i++
		var j15 Inner
		{
			nnn, err := (&j15).Unmarshal(b[i:])
			if err != nil {
				return i, err
			}
			i += nnn
		}
		r.Nested = &j15
	} else {
		i++
		r.Nested = nil
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Arrays) Size() int {
	s := 0
	s += 16
	s += 16
	for j16 := 0; j16 < 2; j16++ {
		s += codec.UvarintSize(uint64(len(r.Tags[j16]))) + len(r.Tags[j16])
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Arrays) Marshal(b []byte) int {
	i := 0
	i += copy(b[i:], r.Hash[:])
	for j17 := 0; j17 < 4; j17++ {
		codec.PutU32(b[i:], uint32(r.Quad[j17]))
		i += 4
	}
	for j18 := 0; j18 < 2; j18++ {
		i += codec.PutUvarint(b[i:], uint64(len(r.Tags[j18])))
		i += copy(b[i:], codec.S2B(r.Tags[j18]))
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Arrays) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 16 {
		return i, codec.ErrShortBuffer
	}
	copy(r.Hash[:], b[i:i+16])
	i += 16
	for j19 := 0; j19 < 4; j19++ {
		if len(b)-i < 4 {
			return i, codec.ErrShortBuffer
		}
		r.Quad[j19] = int32(codec.U32(b[i:]))
		i += 4
	}
	for j20 := 0; j20 < 2; j20++ {
		nn, cc = codec.Uvarint(b[i:])
		if cc <= 0 {
			return i, codec.ErrShortBuffer
		}
		i += cc
		if uint64(len(b)-i) < nn {
			return i, codec.ErrShortBuffer
		}
		r.Tags[j20] = string(b[i : i+int(nn)])
		i += int(nn)
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Fixed) Size() int {
	s := 0
	s += 4
	s += 4
	s += 4
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Fixed) Marshal(b []byte) int {
	i := 0
	codec.PutU32(b[i:], uint32(r.X))
	i += 4
	codec.PutU32(b[i:], uint32(r.Y))
	i += 4
	codec.PutU32(b[i:], uint32(r.Z))
	i += 4
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Fixed) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.X = int32(codec.U32(b[i:]))
	i += 4
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.Y = int32(codec.U32(b[i:]))
	i += 4
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.Z = int32(codec.U32(b[i:]))
	i += 4
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Frame) Size() int {
	s := 0
	s += 2
	switch v := r.Sig.(type) {
	case *Ping:
		s += 1 + v.Size()
	case *Pong:
		s += 1 + v.Size()
	case nil:
		s += 1
	default:
		panic("goserde: value is not a registered member of union Signal")
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Frame) Marshal(b []byte) int {
	i := 0
	codec.PutU16(b[i:], uint16(r.ID))
	i += 2
	switch v := r.Sig.(type) {
	case *Ping:
		i += codec.PutUvarint(b[i:], 1)
		i += v.Marshal(b[i:])
	case *Pong:
		i += codec.PutUvarint(b[i:], 2)
		i += v.Marshal(b[i:])
	case nil:
		i += codec.PutUvarint(b[i:], 0)
	default:
		panic("goserde: value is not a registered member of union Signal")
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Frame) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 2 {
		return i, codec.ErrShortBuffer
	}
	r.ID = uint16(codec.U16(b[i:]))
	i += 2
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	switch nn {
	case 0:
		r.Sig = nil
	case 1:
		var j21 Ping
		nnn, err := (&j21).Unmarshal(b[i:])
		if err != nil {
			return i, err
		}
		i += nnn
		r.Sig = &j21
	case 2:
		var j22 Pong
		nnn, err := (&j22).Unmarshal(b[i:])
		if err != nil {
			return i, err
		}
		i += nnn
		r.Sig = &j22
	default:
		return i, codec.ErrUnknownUnionTag
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Inner) Size() int {
	s := 0
	s += 2
	s += codec.UvarintSize(uint64(len(r.B))) + len(r.B)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Inner) Marshal(b []byte) int {
	i := 0
	codec.PutU16(b[i:], uint16(r.A))
	i += 2
	i += codec.PutUvarint(b[i:], uint64(len(r.B)))
	i += copy(b[i:], codec.S2B(r.B))
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Inner) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 2 {
		return i, codec.ErrShortBuffer
	}
	r.A = uint16(codec.U16(b[i:]))
	i += 2
	nn, cc = codec.Uvarint(b[i:])
	if cc <= 0 {
		return i, codec.ErrShortBuffer
	}
	i += cc
	if uint64(len(b)-i) < nn {
		return i, codec.ErrShortBuffer
	}
	r.B = string(b[i : i+int(nn)])
	i += int(nn)
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Ping) Size() int {
	s := 0
	s += 4
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Ping) Marshal(b []byte) int {
	i := 0
	codec.PutU32(b[i:], uint32(r.Seq))
	i += 4
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Ping) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.Seq = uint32(codec.U32(b[i:]))
	i += 4
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Pong) Size() int {
	s := 0
	s += 4
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Pong) Marshal(b []byte) int {
	i := 0
	codec.PutU32(b[i:], uint32(r.Seq))
	i += 4
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// It returns codec.ErrShortBuffer if b is truncated (safe mode).
func (r *Pong) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	if len(b)-i < 4 {
		return i, codec.ErrShortBuffer
	}
	r.Seq = uint32(codec.U32(b[i:]))
	i += 4
	_ = codec.U64
	return i, nil
}
