// MIT License
//
// Copyright (c) 2026 Arsene Tochemey Gandote
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by goserdegen. DO NOT EDIT.

package example

import (
	"github.com/tochemey/goserde/runtime"
	"unsafe"
)

var _ = runtime.UvarintSize // keep import if unused

var _ unsafe.Pointer

// Size returns the fixed wire size of Point (blittable fast path).
func (r *Point) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Point as raw memory into b (trusted bytes, same arch).
func (r *Point) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Point.
func (r *Point) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *User) Size() int {
	s := 0
	s += 8
	s += 2
	s += 4
	s += 1
	s += runtime.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	s += runtime.UvarintSize(uint64(len(r.Nicks)))
	for _, e1 := range r.Nicks {
		s += runtime.UvarintSize(uint64(len(e1))) + len(e1)
	}
	s += runtime.UvarintSize(uint64(len(r.Scores)))
	s += 4 * len(r.Scores)
	s += runtime.UvarintSize(uint64(len(r.Avatar)))
	s += len(r.Avatar)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *User) Marshal(b []byte) int {
	i := 0
	runtime.PutU64(b[i:], uint64(r.ID))
	i += 8
	runtime.PutU16(b[i:], uint16(r.Age))
	i += 2
	runtime.PutU32(b[i:], runtime.F32bits(r.Height))
	i += 4
	if r.Verified {
		b[i] = 1
	} else {
		b[i] = 0
	}
	i++
	i += runtime.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], runtime.S2B(r.Name))
	i += runtime.PutUvarint(b[i:], uint64(len(r.Nicks)))
	for _, e2 := range r.Nicks {
		i += runtime.PutUvarint(b[i:], uint64(len(e2)))
		i += copy(b[i:], runtime.S2B(e2))
	}
	i += runtime.PutUvarint(b[i:], uint64(len(r.Scores)))
	for _, e3 := range r.Scores {
		runtime.PutU32(b[i:], uint32(e3))
		i += 4
	}
	i += runtime.PutUvarint(b[i:], uint64(len(r.Avatar)))
	i += copy(b[i:], r.Avatar)
	_ = runtime.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *User) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	r.ID = uint64(runtime.U64(b[i:]))
	i += 8
	r.Age = uint16(runtime.U16(b[i:]))
	i += 2
	r.Height = runtime.Bitsf32(runtime.U32(b[i:]))
	i += 4
	r.Verified = b[i] != 0
	i++
	nn, cc = runtime.Uvarint(b[i:])
	i += cc
	r.Name = runtime.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = runtime.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Nicks = nil
	} else {
		if cap(r.Nicks) >= int(nn) {
			r.Nicks = r.Nicks[:nn]
		} else {
			r.Nicks = make([]string, nn)
		}
		for j4 := range r.Nicks {
			nn, cc = runtime.Uvarint(b[i:])
			i += cc
			r.Nicks[j4] = runtime.B2S(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	nn, cc = runtime.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Scores = nil
	} else {
		if cap(r.Scores) >= int(nn) {
			r.Scores = r.Scores[:nn]
		} else {
			r.Scores = make([]int32, nn)
		}
		for j5 := range r.Scores {
			r.Scores[j5] = int32(runtime.U32(b[i:]))
			i += 4
		}
	}
	nn, cc = runtime.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Avatar = nil
	} else {
		r.Avatar = b[i : i+int(nn)]
		i += int(nn)
	}
	_ = runtime.U64
	return i, nil
}
