// Code generated by goserdegen v0.1.0. DO NOT EDIT.

package shapes

import (
	"github.com/tochemey/goserde/codec"
	"time"
	"unsafe"
)

var _ = codec.UvarintSize // keep import if unused

var _ unsafe.Pointer

// Size returns the fixed wire size of Circle (blittable fast path).
func (r *Circle) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Circle as raw memory into b (trusted bytes, same arch).
func (r *Circle) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Circle.
func (r *Circle) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *CollectionHeavy) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Counts)))
	for e1, e2 := range r.Counts {
		_ = e1
		_ = e2
		s += codec.UvarintSize(uint64(len(e1))) + len(e1)
		s += 8
	}
	s += codec.UvarintSize(uint64(len(r.Floats)))
	s += 8 * len(r.Floats)
	s += codec.UvarintSize(uint64(len(r.Names)))
	for _, e3 := range r.Names {
		s += codec.UvarintSize(uint64(len(e3))) + len(e3)
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *CollectionHeavy) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Counts)))
	for e4, e5 := range r.Counts {
		i += codec.PutUvarint(b[i:], uint64(len(e4)))
		i += copy(b[i:], codec.S2B(e4))
		codec.PutU64(b[i:], uint64(e5))
		i += 8
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Floats)))
	if len(r.Floats) > 0 {
		i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.Floats[0])), 8*len(r.Floats)))
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Names)))
	for _, e6 := range r.Names {
		i += codec.PutUvarint(b[i:], uint64(len(e6)))
		i += copy(b[i:], codec.S2B(e6))
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *CollectionHeavy) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Counts = nil
	} else {
		j7 := nn
		if r.Counts != nil {
			clear(r.Counts)
		} else {
			r.Counts = make(map[string]int64, j7)
		}
		for j8 := uint64(0); j8 < j7; j8++ {
			var j9 string
			var j10 int64
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			j9 = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
			j10 = int64(codec.U64(b[i:]))
			i += 8
			r.Counts[j9] = j10
		}
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Floats = nil
	} else {
		if cap(r.Floats) >= int(nn) {
			r.Floats = r.Floats[:nn]
		} else {
			r.Floats = make([]float64, nn)
		}
		copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.Floats[0])), 8*int(nn)), b[i:i+8*int(nn)])
		i += 8 * int(nn)
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Names = nil
	} else {
		if cap(r.Names) >= int(nn) {
			r.Names = r.Names[:nn]
		} else {
			r.Names = make([]string, nn)
		}
		for j11 := range r.Names {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			r.Names[j11] = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Drawing) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	switch v := r.Shape.(type) {
	case *Circle:
		s += 1 + v.Size()
	case *Square:
		s += 1 + v.Size()
	case nil:
		s += 1
	default:
		panic("goserde: value is not a registered member of union Geometry")
	}
	s += codec.UvarintSize(uint64(len(r.Layers)))
	for _, e12 := range r.Layers {
		switch v := e12.(type) {
		case *Circle:
			s += 1 + v.Size()
		case *Square:
			s += 1 + v.Size()
		case nil:
			s += 1
		default:
			panic("goserde: value is not a registered member of union Geometry")
		}
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Drawing) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	switch v := r.Shape.(type) {
	case *Circle:
		i += codec.PutUvarint(b[i:], 1)
		i += v.Marshal(b[i:])
	case *Square:
		i += codec.PutUvarint(b[i:], 2)
		i += v.Marshal(b[i:])
	case nil:
		i += codec.PutUvarint(b[i:], 0)
	default:
		panic("goserde: value is not a registered member of union Geometry")
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Layers)))
	for _, e13 := range r.Layers {
		switch v := e13.(type) {
		case *Circle:
			i += codec.PutUvarint(b[i:], 1)
			i += v.Marshal(b[i:])
		case *Square:
			i += codec.PutUvarint(b[i:], 2)
			i += v.Marshal(b[i:])
		case nil:
			i += codec.PutUvarint(b[i:], 0)
		default:
			panic("goserde: value is not a registered member of union Geometry")
		}
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Drawing) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	switch nn {
	case 0:
		r.Shape = nil
	case 1:
		var j14 Circle
		nnn, _ := (&j14).Unmarshal(b[i:])
		i += nnn
		r.Shape = &j14
	case 2:
		var j15 Square
		nnn, _ := (&j15).Unmarshal(b[i:])
		i += nnn
		r.Shape = &j15
	default:
		return i, codec.ErrUnknownUnionTag
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Layers = nil
	} else {
		if cap(r.Layers) >= int(nn) {
			r.Layers = r.Layers[:nn]
		} else {
			r.Layers = make([]Geometry, nn)
		}
		for j16 := range r.Layers {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			switch nn {
			case 0:
				r.Layers[j16] = nil
			case 1:
				var j17 Circle
				nnn, _ := (&j17).Unmarshal(b[i:])
				i += nnn
				r.Layers[j16] = &j17
			case 2:
				var j18 Square
				nnn, _ := (&j18).Unmarshal(b[i:])
				i += nnn
				r.Layers[j16] = &j18
			default:
				return i, codec.ErrUnknownUnionTag
			}
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of FixedArrays (blittable fast path).
func (r *FixedArrays) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies FixedArrays as raw memory into b (trusted bytes, same arch).
func (r *FixedArrays) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into FixedArrays.
func (r *FixedArrays) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *FlatMixed) Size() int {
	s := 0
	s += 8
	s += 8
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	s += codec.UvarintSize(uint64(len(r.Data)))
	s += len(r.Data)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *FlatMixed) Marshal(b []byte) int {
	i := 0
	codec.PutU64(b[i:], uint64(r.ID))
	i += 8
	codec.PutU64(b[i:], codec.F64bits(r.Ratio))
	i += 8
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	i += codec.PutUvarint(b[i:], uint64(len(r.Data)))
	i += copy(b[i:], r.Data)
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *FlatMixed) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	r.ID = uint64(codec.U64(b[i:]))
	i += 8
	r.Ratio = codec.Bitsf64(codec.U64(b[i:]))
	i += 8
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Data = nil
	} else {
		r.Data = b[i : i+int(nn)]
		i += int(nn)
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of Inner (blittable fast path).
func (r *Inner) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Inner as raw memory into b (trusted bytes, same arch).
func (r *Inner) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Inner.
func (r *Inner) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *MixedArrays) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	for j19 := 0; j19 < 3; j19++ {
		s += codec.UvarintSize(uint64(len(r.Words[j19]))) + len(r.Words[j19])
	}
	for j20 := 0; j20 < 2; j20++ {
		s += (&r.Points[j20]).Size()
	}
	s += 8
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *MixedArrays) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	for j21 := 0; j21 < 3; j21++ {
		i += codec.PutUvarint(b[i:], uint64(len(r.Words[j21])))
		i += copy(b[i:], codec.S2B(r.Words[j21]))
	}
	for j22 := 0; j22 < 2; j22++ {
		i += (&r.Points[j22]).Marshal(b[i:])
	}
	i += copy(b[i:], r.Bytes[:])
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *MixedArrays) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	for j23 := 0; j23 < 3; j23++ {
		nn, cc = codec.Uvarint(b[i:])
		i += cc
		r.Words[j23] = codec.B2S(b[i : i+int(nn)])
		i += int(nn)
	}
	for j24 := 0; j24 < 2; j24++ {
		{
			nnn, _ := (&r.Points[j24]).Unmarshal(b[i:])
			i += nnn
		}
	}
	copy(r.Bytes[:], b[i:i+8])
	i += 8
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of NamedFixed (blittable fast path).
func (r *NamedFixed) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies NamedFixed as raw memory into b (trusted bytes, same arch).
func (r *NamedFixed) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into NamedFixed.
func (r *NamedFixed) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *NamedScalars) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += codec.UvarintSize(uint64(len(r.Palette)))
	s += 1 * len(r.Palette)
	s += 4
	s += codec.UvarintSize(uint64(len(r.Levels)))
	s += 4 * len(r.Levels)
	s += 1
	if r.Accent != nil {
		s += 1
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *NamedScalars) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	i += codec.PutUvarint(b[i:], uint64(len(r.Palette)))
	if len(r.Palette) > 0 {
		i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.Palette[0])), len(r.Palette)))
	}
	i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.Swatch[0])), 4))
	i += codec.PutUvarint(b[i:], uint64(len(r.Levels)))
	if len(r.Levels) > 0 {
		i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.Levels[0])), 4*len(r.Levels)))
	}
	if r.Accent != nil {
		b[i] = 1
		i++
		b[i] = byte((*r.Accent))
		i++
	} else {
		b[i] = 0
		i++
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *NamedScalars) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Palette = nil
	} else {
		if cap(r.Palette) >= int(nn) {
			r.Palette = r.Palette[:nn]
		} else {
			r.Palette = make([]Hue, nn)
		}
		copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.Palette[0])), int(nn)), b[i:i+int(nn)])
		i += int(nn)
	}
	copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.Swatch[0])), 4), b[i:i+4])
	i += 4
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Levels = nil
	} else {
		if cap(r.Levels) >= int(nn) {
			r.Levels = r.Levels[:nn]
		} else {
			r.Levels = make([]Grade, nn)
		}
		copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.Levels[0])), 4*int(nn)), b[i:i+4*int(nn)])
		i += 4 * int(nn)
	}
	if b[i] != 0 {
		i++
		var j25 Hue
		j25 = Hue(b[i])
		i++
		r.Accent = &j25
	} else {
		i++
		r.Accent = nil
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Nested) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += (&r.Pos).Size()
	s += 1
	if r.Opt != nil {
		s += (&(*r.Opt)).Size()
	}
	s += codec.UvarintSize(uint64(len(r.Path)))
	for _, e26 := range r.Path {
		s += (&e26).Size()
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Nested) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	i += (&r.Pos).Marshal(b[i:])
	if r.Opt != nil {
		b[i] = 1
		i++
		i += (&(*r.Opt)).Marshal(b[i:])
	} else {
		b[i] = 0
		i++
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Path)))
	for _, e27 := range r.Path {
		i += (&e27).Marshal(b[i:])
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Nested) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	{
		nnn, _ := (&r.Pos).Unmarshal(b[i:])
		i += nnn
	}
	if b[i] != 0 {
		i++
		var j28 Inner
		{
			nnn, _ := (&j28).Unmarshal(b[i:])
			i += nnn
		}
		r.Opt = &j28
	} else {
		i++
		r.Opt = nil
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Path = nil
	} else {
		if cap(r.Path) >= int(nn) {
			r.Path = r.Path[:nn]
		} else {
			r.Path = make([]Inner, nn)
		}
		for j29 := range r.Path {
			{
				nnn, _ := (&r.Path[j29]).Unmarshal(b[i:])
				i += nnn
			}
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *NumericBulk) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += codec.UvarintSize(uint64(len(r.U16s)))
	s += 2 * len(r.U16s)
	s += codec.UvarintSize(uint64(len(r.F64s)))
	s += 8 * len(r.F64s)
	s += 16
	s += codec.UvarintSize(uint64(len(r.Ints)))
	s += 8 * len(r.Ints)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *NumericBulk) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	i += codec.PutUvarint(b[i:], uint64(len(r.U16s)))
	if len(r.U16s) > 0 {
		i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.U16s[0])), 2*len(r.U16s)))
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.F64s)))
	if len(r.F64s) > 0 {
		i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.F64s[0])), 8*len(r.F64s)))
	}
	i += copy(b[i:], unsafe.Slice((*byte)(unsafe.Pointer(&r.Quad[0])), 16))
	i += codec.PutUvarint(b[i:], uint64(len(r.Ints)))
	for _, e30 := range r.Ints {
		codec.PutU64(b[i:], uint64(e30))
		i += 8
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *NumericBulk) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.U16s = nil
	} else {
		if cap(r.U16s) >= int(nn) {
			r.U16s = r.U16s[:nn]
		} else {
			r.U16s = make([]uint16, nn)
		}
		copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.U16s[0])), 2*int(nn)), b[i:i+2*int(nn)])
		i += 2 * int(nn)
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.F64s = nil
	} else {
		if cap(r.F64s) >= int(nn) {
			r.F64s = r.F64s[:nn]
		} else {
			r.F64s = make([]float64, nn)
		}
		copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.F64s[0])), 8*int(nn)), b[i:i+8*int(nn)])
		i += 8 * int(nn)
	}
	copy(unsafe.Slice((*byte)(unsafe.Pointer(&r.Quad[0])), 16), b[i:i+16])
	i += 16
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Ints = nil
	} else {
		if cap(r.Ints) >= int(nn) {
			r.Ints = r.Ints[:nn]
		} else {
			r.Ints = make([]int, nn)
		}
		for j31 := range r.Ints {
			r.Ints[j31] = int(codec.U64(b[i:]))
			i += 8
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of SmallFixed (blittable fast path).
func (r *SmallFixed) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies SmallFixed as raw memory into b (trusted bytes, same arch).
func (r *SmallFixed) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into SmallFixed.
func (r *SmallFixed) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the fixed wire size of Square (blittable fast path).
func (r *Square) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Square as raw memory into b (trusted bytes, same arch).
func (r *Square) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Square.
func (r *Square) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *StringHeavy) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Title))) + len(r.Title)
	s += codec.UvarintSize(uint64(len(r.Body))) + len(r.Body)
	s += codec.UvarintSize(uint64(len(r.Tags)))
	for _, e32 := range r.Tags {
		s += codec.UvarintSize(uint64(len(e32))) + len(e32)
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *StringHeavy) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Title)))
	i += copy(b[i:], codec.S2B(r.Title))
	i += codec.PutUvarint(b[i:], uint64(len(r.Body)))
	i += copy(b[i:], codec.S2B(r.Body))
	i += codec.PutUvarint(b[i:], uint64(len(r.Tags)))
	for _, e33 := range r.Tags {
		i += codec.PutUvarint(b[i:], uint64(len(e33)))
		i += copy(b[i:], codec.S2B(e33))
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *StringHeavy) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Title = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Body = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Tags = nil
	} else {
		if cap(r.Tags) >= int(nn) {
			r.Tags = r.Tags[:nn]
		} else {
			r.Tags = make([]string, nn)
		}
		for j34 := range r.Tags {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			r.Tags[j34] = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Tagged) Size() int {
	s := 0
	s += 8
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Tagged) Marshal(b []byte) int {
	i := 0
	codec.PutU64(b[i:], uint64(r.ID))
	i += 8
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Tagged) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	r.ID = int64(codec.U64(b[i:]))
	i += 8
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *TimeStruct) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += 8
	s += 1
	if r.Updated != nil {
		s += 8
	}
	s += codec.UvarintSize(uint64(len(r.Stamps)))
	s += 8 * len(r.Stamps)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *TimeStruct) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	codec.PutU64(b[i:], uint64(r.Created.UnixNano()))
	i += 8
	if r.Updated != nil {
		b[i] = 1
		i++
		codec.PutU64(b[i:], uint64((*r.Updated).UnixNano()))
		i += 8
	} else {
		b[i] = 0
		i++
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Stamps)))
	for _, e35 := range r.Stamps {
		codec.PutU64(b[i:], uint64(e35.UnixNano()))
		i += 8
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *TimeStruct) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	r.Created = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
	i += 8
	if b[i] != 0 {
		i++
		var j36 time.Time
		j36 = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
		i += 8
		r.Updated = &j36
	} else {
		i++
		r.Updated = nil
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Stamps = nil
	} else {
		if cap(r.Stamps) >= int(nn) {
			r.Stamps = r.Stamps[:nn]
		} else {
			r.Stamps = make([]time.Time, nn)
		}
		for j37 := range r.Stamps {
			r.Stamps[j37] = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
			i += 8
		}
	}
	_ = codec.U64
	return i, nil
}
