// Code generated by goserdegen v0.1.0. DO NOT EDIT.

package shapes

import (
	"github.com/tochemey/goserde/codec"
	"time"
	"unsafe"
)

var _ = codec.UvarintSize // keep import if unused

var _ unsafe.Pointer

// Size returns the fixed wire size of Circle (blittable fast path).
func (r *Circle) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Circle as raw memory into b (trusted bytes, same arch).
func (r *Circle) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Circle.
func (r *Circle) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *CollectionHeavy) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Counts)))
	for e1, e2 := range r.Counts {
		_ = e1
		_ = e2
		s += codec.UvarintSize(uint64(len(e1))) + len(e1)
		s += 8
	}
	s += codec.UvarintSize(uint64(len(r.Floats)))
	s += 8 * len(r.Floats)
	s += codec.UvarintSize(uint64(len(r.Names)))
	for _, e3 := range r.Names {
		s += codec.UvarintSize(uint64(len(e3))) + len(e3)
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *CollectionHeavy) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Counts)))
	for e4, e5 := range r.Counts {
		i += codec.PutUvarint(b[i:], uint64(len(e4)))
		i += copy(b[i:], codec.S2B(e4))
		codec.PutU64(b[i:], uint64(e5))
		i += 8
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Floats)))
	for _, e6 := range r.Floats {
		codec.PutU64(b[i:], codec.F64bits(e6))
		i += 8
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Names)))
	for _, e7 := range r.Names {
		i += codec.PutUvarint(b[i:], uint64(len(e7)))
		i += copy(b[i:], codec.S2B(e7))
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *CollectionHeavy) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Counts = nil
	} else {
		j8 := nn
		if r.Counts != nil {
			clear(r.Counts)
		} else {
			r.Counts = make(map[string]int64, j8)
		}
		for j9 := uint64(0); j9 < j8; j9++ {
			var j10 string
			var j11 int64
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			j10 = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
			j11 = int64(codec.U64(b[i:]))
			i += 8
			r.Counts[j10] = j11
		}
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Floats = nil
	} else {
		if cap(r.Floats) >= int(nn) {
			r.Floats = r.Floats[:nn]
		} else {
			r.Floats = make([]float64, nn)
		}
		for j12 := range r.Floats {
			r.Floats[j12] = codec.Bitsf64(codec.U64(b[i:]))
			i += 8
		}
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Names = nil
	} else {
		if cap(r.Names) >= int(nn) {
			r.Names = r.Names[:nn]
		} else {
			r.Names = make([]string, nn)
		}
		for j13 := range r.Names {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			r.Names[j13] = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Drawing) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	switch v := r.Shape.(type) {
	case *Circle:
		s += 1 + v.Size()
	case *Square:
		s += 1 + v.Size()
	case nil:
		s += 1
	default:
		panic("goserde: value is not a registered member of union Geometry")
	}
	s += codec.UvarintSize(uint64(len(r.Layers)))
	for _, e14 := range r.Layers {
		switch v := e14.(type) {
		case *Circle:
			s += 1 + v.Size()
		case *Square:
			s += 1 + v.Size()
		case nil:
			s += 1
		default:
			panic("goserde: value is not a registered member of union Geometry")
		}
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Drawing) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	switch v := r.Shape.(type) {
	case *Circle:
		i += codec.PutUvarint(b[i:], 1)
		i += v.Marshal(b[i:])
	case *Square:
		i += codec.PutUvarint(b[i:], 2)
		i += v.Marshal(b[i:])
	case nil:
		i += codec.PutUvarint(b[i:], 0)
	default:
		panic("goserde: value is not a registered member of union Geometry")
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Layers)))
	for _, e15 := range r.Layers {
		switch v := e15.(type) {
		case *Circle:
			i += codec.PutUvarint(b[i:], 1)
			i += v.Marshal(b[i:])
		case *Square:
			i += codec.PutUvarint(b[i:], 2)
			i += v.Marshal(b[i:])
		case nil:
			i += codec.PutUvarint(b[i:], 0)
		default:
			panic("goserde: value is not a registered member of union Geometry")
		}
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Drawing) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	switch nn {
	case 0:
		r.Shape = nil
	case 1:
		var j16 Circle
		nnn, _ := (&j16).Unmarshal(b[i:])
		i += nnn
		r.Shape = &j16
	case 2:
		var j17 Square
		nnn, _ := (&j17).Unmarshal(b[i:])
		i += nnn
		r.Shape = &j17
	default:
		return i, codec.ErrUnknownUnionTag
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Layers = nil
	} else {
		if cap(r.Layers) >= int(nn) {
			r.Layers = r.Layers[:nn]
		} else {
			r.Layers = make([]Geometry, nn)
		}
		for j18 := range r.Layers {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			switch nn {
			case 0:
				r.Layers[j18] = nil
			case 1:
				var j19 Circle
				nnn, _ := (&j19).Unmarshal(b[i:])
				i += nnn
				r.Layers[j18] = &j19
			case 2:
				var j20 Square
				nnn, _ := (&j20).Unmarshal(b[i:])
				i += nnn
				r.Layers[j18] = &j20
			default:
				return i, codec.ErrUnknownUnionTag
			}
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of FixedArrays (blittable fast path).
func (r *FixedArrays) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies FixedArrays as raw memory into b (trusted bytes, same arch).
func (r *FixedArrays) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into FixedArrays.
func (r *FixedArrays) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *FlatMixed) Size() int {
	s := 0
	s += 8
	s += 8
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	s += codec.UvarintSize(uint64(len(r.Data)))
	s += len(r.Data)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *FlatMixed) Marshal(b []byte) int {
	i := 0
	codec.PutU64(b[i:], uint64(r.ID))
	i += 8
	codec.PutU64(b[i:], codec.F64bits(r.Ratio))
	i += 8
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	i += codec.PutUvarint(b[i:], uint64(len(r.Data)))
	i += copy(b[i:], r.Data)
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *FlatMixed) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	r.ID = uint64(codec.U64(b[i:]))
	i += 8
	r.Ratio = codec.Bitsf64(codec.U64(b[i:]))
	i += 8
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Data = nil
	} else {
		r.Data = b[i : i+int(nn)]
		i += int(nn)
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of Inner (blittable fast path).
func (r *Inner) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Inner as raw memory into b (trusted bytes, same arch).
func (r *Inner) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Inner.
func (r *Inner) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *MixedArrays) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	for j21 := 0; j21 < 3; j21++ {
		s += codec.UvarintSize(uint64(len(r.Words[j21]))) + len(r.Words[j21])
	}
	for j22 := 0; j22 < 2; j22++ {
		s += (&r.Points[j22]).Size()
	}
	s += 8
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *MixedArrays) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	for j23 := 0; j23 < 3; j23++ {
		i += codec.PutUvarint(b[i:], uint64(len(r.Words[j23])))
		i += copy(b[i:], codec.S2B(r.Words[j23]))
	}
	for j24 := 0; j24 < 2; j24++ {
		i += (&r.Points[j24]).Marshal(b[i:])
	}
	i += copy(b[i:], r.Bytes[:])
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *MixedArrays) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	for j25 := 0; j25 < 3; j25++ {
		nn, cc = codec.Uvarint(b[i:])
		i += cc
		r.Words[j25] = codec.B2S(b[i : i+int(nn)])
		i += int(nn)
	}
	for j26 := 0; j26 < 2; j26++ {
		{
			nnn, _ := (&r.Points[j26]).Unmarshal(b[i:])
			i += nnn
		}
	}
	copy(r.Bytes[:], b[i:i+8])
	i += 8
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of NamedFixed (blittable fast path).
func (r *NamedFixed) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies NamedFixed as raw memory into b (trusted bytes, same arch).
func (r *NamedFixed) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into NamedFixed.
func (r *NamedFixed) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *NamedScalars) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += codec.UvarintSize(uint64(len(r.Palette)))
	s += 1 * len(r.Palette)
	s += 4
	s += codec.UvarintSize(uint64(len(r.Levels)))
	s += 4 * len(r.Levels)
	s += 1
	if r.Accent != nil {
		s += 1
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *NamedScalars) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	i += codec.PutUvarint(b[i:], uint64(len(r.Palette)))
	for _, e27 := range r.Palette {
		b[i] = byte(e27)
		i++
	}
	for j28 := 0; j28 < 4; j28++ {
		b[i] = byte(r.Swatch[j28])
		i++
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Levels)))
	for _, e29 := range r.Levels {
		codec.PutU32(b[i:], uint32(e29))
		i += 4
	}
	if r.Accent != nil {
		b[i] = 1
		i++
		b[i] = byte((*r.Accent))
		i++
	} else {
		b[i] = 0
		i++
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *NamedScalars) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Palette = nil
	} else {
		if cap(r.Palette) >= int(nn) {
			r.Palette = r.Palette[:nn]
		} else {
			r.Palette = make([]Hue, nn)
		}
		for j30 := range r.Palette {
			r.Palette[j30] = Hue(b[i])
			i++
		}
	}
	for j31 := 0; j31 < 4; j31++ {
		r.Swatch[j31] = Hue(b[i])
		i++
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Levels = nil
	} else {
		if cap(r.Levels) >= int(nn) {
			r.Levels = r.Levels[:nn]
		} else {
			r.Levels = make([]Grade, nn)
		}
		for j32 := range r.Levels {
			r.Levels[j32] = Grade(codec.U32(b[i:]))
			i += 4
		}
	}
	if b[i] != 0 {
		i++
		var j33 Hue
		j33 = Hue(b[i])
		i++
		r.Accent = &j33
	} else {
		i++
		r.Accent = nil
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Nested) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += (&r.Pos).Size()
	s += 1
	if r.Opt != nil {
		s += (&(*r.Opt)).Size()
	}
	s += codec.UvarintSize(uint64(len(r.Path)))
	for _, e34 := range r.Path {
		s += (&e34).Size()
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Nested) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	i += (&r.Pos).Marshal(b[i:])
	if r.Opt != nil {
		b[i] = 1
		i++
		i += (&(*r.Opt)).Marshal(b[i:])
	} else {
		b[i] = 0
		i++
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Path)))
	for _, e35 := range r.Path {
		i += (&e35).Marshal(b[i:])
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Nested) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	{
		nnn, _ := (&r.Pos).Unmarshal(b[i:])
		i += nnn
	}
	if b[i] != 0 {
		i++
		var j36 Inner
		{
			nnn, _ := (&j36).Unmarshal(b[i:])
			i += nnn
		}
		r.Opt = &j36
	} else {
		i++
		r.Opt = nil
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Path = nil
	} else {
		if cap(r.Path) >= int(nn) {
			r.Path = r.Path[:nn]
		} else {
			r.Path = make([]Inner, nn)
		}
		for j37 := range r.Path {
			{
				nnn, _ := (&r.Path[j37]).Unmarshal(b[i:])
				i += nnn
			}
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the fixed wire size of SmallFixed (blittable fast path).
func (r *SmallFixed) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies SmallFixed as raw memory into b (trusted bytes, same arch).
func (r *SmallFixed) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into SmallFixed.
func (r *SmallFixed) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the fixed wire size of Square (blittable fast path).
func (r *Square) Size() int {
	return int(unsafe.Sizeof(*r))
}

// Marshal copies Square as raw memory into b (trusted bytes, same arch).
func (r *Square) Marshal(b []byte) int {
	n := int(unsafe.Sizeof(*r))
	copy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))
	return n
}

// Unmarshal copies raw memory from b back into Square.
func (r *Square) Unmarshal(b []byte) (int, error) {
	n := int(unsafe.Sizeof(*r))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)
	return n, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *StringHeavy) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Title))) + len(r.Title)
	s += codec.UvarintSize(uint64(len(r.Body))) + len(r.Body)
	s += codec.UvarintSize(uint64(len(r.Tags)))
	for _, e38 := range r.Tags {
		s += codec.UvarintSize(uint64(len(e38))) + len(e38)
	}
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *StringHeavy) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Title)))
	i += copy(b[i:], codec.S2B(r.Title))
	i += codec.PutUvarint(b[i:], uint64(len(r.Body)))
	i += copy(b[i:], codec.S2B(r.Body))
	i += codec.PutUvarint(b[i:], uint64(len(r.Tags)))
	for _, e39 := range r.Tags {
		i += codec.PutUvarint(b[i:], uint64(len(e39)))
		i += copy(b[i:], codec.S2B(e39))
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *StringHeavy) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Title = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Body = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Tags = nil
	} else {
		if cap(r.Tags) >= int(nn) {
			r.Tags = r.Tags[:nn]
		} else {
			r.Tags = make([]string, nn)
		}
		for j40 := range r.Tags {
			nn, cc = codec.Uvarint(b[i:])
			i += cc
			r.Tags[j40] = codec.B2S(b[i : i+int(nn)])
			i += int(nn)
		}
	}
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *Tagged) Size() int {
	s := 0
	s += 8
	s += codec.UvarintSize(uint64(len(r.Name))) + len(r.Name)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *Tagged) Marshal(b []byte) int {
	i := 0
	codec.PutU64(b[i:], uint64(r.ID))
	i += 8
	i += codec.PutUvarint(b[i:], uint64(len(r.Name)))
	i += copy(b[i:], codec.S2B(r.Name))
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *Tagged) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	r.ID = int64(codec.U64(b[i:]))
	i += 8
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Name = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	_ = codec.U64
	return i, nil
}

// Size returns the exact number of bytes Marshal will write for the receiver.
func (r *TimeStruct) Size() int {
	s := 0
	s += codec.UvarintSize(uint64(len(r.Label))) + len(r.Label)
	s += 8
	s += 1
	if r.Updated != nil {
		s += 8
	}
	s += codec.UvarintSize(uint64(len(r.Stamps)))
	s += 8 * len(r.Stamps)
	return s
}

// Marshal encodes the receiver into b, which must be at least Size() bytes,
// and returns the number of bytes written.
func (r *TimeStruct) Marshal(b []byte) int {
	i := 0
	i += codec.PutUvarint(b[i:], uint64(len(r.Label)))
	i += copy(b[i:], codec.S2B(r.Label))
	codec.PutU64(b[i:], uint64(r.Created.UnixNano()))
	i += 8
	if r.Updated != nil {
		b[i] = 1
		i++
		codec.PutU64(b[i:], uint64((*r.Updated).UnixNano()))
		i += 8
	} else {
		b[i] = 0
		i++
	}
	i += codec.PutUvarint(b[i:], uint64(len(r.Stamps)))
	for _, e41 := range r.Stamps {
		codec.PutU64(b[i:], uint64(e41.UnixNano()))
		i += 8
	}
	_ = codec.PutU64
	return i
}

// Unmarshal decodes the receiver from b and returns the number of bytes consumed.
// The returned error is always nil; truncated input may panic (fast mode).
func (r *TimeStruct) Unmarshal(b []byte) (int, error) {
	i := 0
	var nn uint64
	var cc int
	_ = nn
	_ = cc
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	r.Label = codec.B2S(b[i : i+int(nn)])
	i += int(nn)
	r.Created = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
	i += 8
	if b[i] != 0 {
		i++
		var j42 time.Time
		j42 = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
		i += 8
		r.Updated = &j42
	} else {
		i++
		r.Updated = nil
	}
	nn, cc = codec.Uvarint(b[i:])
	i += cc
	if nn == 0 {
		r.Stamps = nil
	} else {
		if cap(r.Stamps) >= int(nn) {
			r.Stamps = r.Stamps[:nn]
		} else {
			r.Stamps = make([]time.Time, nn)
		}
		for j43 := range r.Stamps {
			r.Stamps[j43] = time.Unix(0, int64(codec.U64(b[i:]))).UTC()
			i += 8
		}
	}
	_ = codec.U64
	return i, nil
}
