// MIT License
//
// Copyright (c) 2026 Arsene Tochemey Gandote
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"reflect"
	"slices"
)

const (
	// structTagKey is the struct-tag key goserde reads for per-field control,
	// e.g. `goserde:"-"`.
	structTagKey = "goserde"
	// tagSkip is the tag value that excludes a field from the wire format.
	tagSkip = "-"
)

// field is one struct field we know how to serialize.
type field struct {
	name string     // exported Go field name
	typ  types.Type // its declared type, used to pick the codec
}

// emitf writes a formatted fragment of generated code into b. Writes to a
// bytes.Buffer never fail, so the returned error is intentionally discarded;
// routing every emission through this helper keeps that decision in one place.
func emitf(b *bytes.Buffer, format string, args ...any) {
	_, _ = fmt.Fprintf(b, format, args...)
}

// generate type-checks the loaded package, emits a codec for every target, and
// returns the gofmt'd source of the output file.
func (g *generator) generate() ([]byte, error) {
	var b bytes.Buffer

	needsUnsafe := false

	for _, t := range g.targets {
		fs, err := g.fieldsOf(t)
		if err != nil {
			return nil, err
		}

		if !g.safe && g.blittable(fs) {
			// Fixed-width struct: single memory copy (fastape/gencode-fixed tier).
			// Safe mode skips this native-memory path for portable, field-by-field
			// little-endian encoding (no unsafe, no memmove).
			g.emitBlitSize(&b, t)
			g.emitBlitMarshal(&b, t)
			g.emitBlitUnmarshal(&b, t)
			needsUnsafe = true
			continue
		}

		g.emitSize(&b, t, fs)
		g.emitMarshal(&b, t, fs)
		g.emitUnmarshal(&b, t, fs)
	}

	out := &bytes.Buffer{}
	emitf(out, "// Code generated by goserdegen %s. DO NOT EDIT.\n\n", version)
	emitf(out, "package %s\n\n", g.pkgName)
	emitf(out, "import (\n\t%q\n", g.codecPkg)

	if g.usedTime {
		emitf(out, "\t\"time\"\n")
	}

	if needsUnsafe {
		emitf(out, "\t\"unsafe\"\n")
	}

	emitf(out, ")\n\n")
	emitf(out, "var _ = %s.UvarintSize // keep import if unused\n\n", g.codecQual)

	if needsUnsafe {
		emitf(out, "var _ unsafe.Pointer\n\n")
	}

	_, _ = out.Write(b.Bytes())

	src, err := formatSource(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("gofmt: %w", err)
	}

	return src, nil
}

// formatSource is indirected (defaulting to go/format.Source) so a test can
// exercise generate's gofmt-failure path, which is otherwise unreachable because
// the emitter only ever produces valid Go.
var formatSource = format.Source

// fieldsOf returns the exported, serializable fields of t in declaration order,
// or an error naming the first field whose type is unsupported.
func (g *generator) fieldsOf(t *types.Named) ([]field, error) {
	st := t.Underlying().(*types.Struct)

	var fs []field

	for i := range st.NumFields() {
		f := st.Field(i)

		if !f.Exported() {
			continue // unexported fields are skipped (mirrors most codegen serializers)
		}

		if reflect.StructTag(st.Tag(i)).Get(structTagKey) == tagSkip {
			continue // explicitly excluded via `goserde:"-"`, even if its type is unsupported
		}

		if err := g.supported(f.Type()); err != nil {
			return nil, fmt.Errorf("%s.%s: %w", t.Obj().Name(), f.Name(), err)
		}

		fs = append(fs, field{name: f.Name(), typ: f.Type()})
	}

	return fs, nil
}

// supported reports whether a type is handled by the current generator.
func (g *generator) supported(t types.Type) error {
	if isTime(t) {
		return nil // time.Time is serialized as int64 unix-nanoseconds
	}

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
			types.Int8, types.Int16, types.Int32, types.Int64,
			types.Uint, types.Int, types.Float32, types.Float64, types.String:
			return nil
		}

		return fmt.Errorf("unsupported basic type %s", u)
	case *types.Slice:
		return g.supported(u.Elem())
	case *types.Array:
		return g.supported(u.Elem())
	case *types.Pointer:
		return g.supported(u.Elem())
	case *types.Map:
		if err := g.supported(u.Key()); err != nil {
			return err
		}

		return g.supported(u.Elem())
	case *types.Struct:
		// Named struct field: require it to also be a generation target so it
		// has Size/Marshal/Unmarshal methods we can delegate to.
		if named, ok := t.(*types.Named); ok {
			if g.isTarget(named) {
				return nil
			}

			return fmt.Errorf("nested struct %s must also have //%s", named.Obj().Name(), marker)
		}

		return fmt.Errorf("anonymous struct fields are not supported")
	case *types.Interface:
		// Interface fields are only supported as declared tagged unions.
		if _, ok := g.unionMembersOf(t); ok {
			return nil
		}

		return fmt.Errorf("interface field %s must be declared with //%s", t, unionMarker)
	default:
		return fmt.Errorf("unsupported type %s", t)
	}
}

// isTarget reports whether n is one of the structs we are generating codecs for.
func (g *generator) isTarget(n *types.Named) bool {
	return slices.Contains(g.targets, n)
}

// unionMembersOf returns the ordered member types of t when t is a named
// interface registered as a tagged union, and reports whether it is one.
func (g *generator) unionMembersOf(t types.Type) ([]*types.Named, bool) {
	named, ok := t.(*types.Named)
	if !ok {
		return nil, false
	}

	members, ok := g.unions[named]

	return members, ok
}

// emitSize writes the Size method for t, which returns the exact encoded length.
func (g *generator) emitSize(b *bytes.Buffer, t *types.Named, fs []field) {
	recv := t.Obj().Name()

	emitf(b, "// Size returns the exact number of bytes Marshal will write for the receiver.\n")
	emitf(b, "func (r *%s) Size() int {\n\ts := 0\n", recv)

	for _, f := range fs {
		g.sizeExpr(b, "r."+f.name, f.typ)
	}

	emitf(b, "\treturn s\n}\n\n")
}

// sizeExpr appends to s the byte count contributed by the value ref of type t.
func (g *generator) sizeExpr(b *bytes.Buffer, ref string, t types.Type) {
	q := g.codecQual

	if isTime(t) {
		g.usedTime = true
		emitf(b, "\ts += 8\n") // int64 unix-nanoseconds
		return
	}

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool, types.Uint8, types.Int8:
			emitf(b, "\ts += 1\n")
		case types.Uint16, types.Int16:
			emitf(b, "\ts += 2\n")
		case types.Uint32, types.Int32, types.Float32:
			emitf(b, "\ts += 4\n")
		case types.Uint64, types.Int64, types.Uint, types.Int, types.Float64:
			emitf(b, "\ts += 8\n")
		case types.String:
			emitf(b, "\ts += %s.UvarintSize(uint64(len(%s))) + len(%s)\n", q, ref, ref)
		}
	case *types.Slice:
		emitf(b, "\ts += %s.UvarintSize(uint64(len(%s)))\n", q, ref)

		if isBytes(u) {
			emitf(b, "\ts += len(%s)\n", ref)
			return
		}

		esz, fixed := fixedSize(u.Elem())
		if fixed {
			emitf(b, "\ts += %d*len(%s)\n", esz, ref)
			return
		}

		// variable-size elements (e.g. []string)
		iv := freshVar()
		emitf(b, "\tfor _, %s := range %s {\n", iv, ref)
		g.sizeExpr(b, iv, u.Elem())
		emitf(b, "\t}\n")
	case *types.Array:
		// Fixed length, no length prefix on the wire.
		if esz, fixed := fixedSize(u.Elem()); fixed {
			emitf(b, "\ts += %d\n", int(u.Len())*esz)
			return
		}

		iv := freshIdx()
		emitf(b, "\tfor %s := 0; %s < %d; %s++ {\n", iv, iv, u.Len(), iv)
		g.sizeExpr(b, fmt.Sprintf("%s[%s]", ref, iv), u.Elem())
		emitf(b, "\t}\n")
	case *types.Pointer:
		emitf(b, "\ts += 1\n") // 1-byte nil flag
		emitf(b, "\tif %s != nil {\n", ref)
		g.sizeExpr(b, "(*"+ref+")", u.Elem())
		emitf(b, "\t}\n")
	case *types.Map:
		emitf(b, "\ts += %s.UvarintSize(uint64(len(%s)))\n", q, ref)
		kv, vv := freshVar(), freshVar()
		emitf(b, "\tfor %s, %s := range %s {\n", kv, vv, ref)
		emitf(b, "\t\t_ = %s\n\t\t_ = %s\n", kv, vv)
		g.sizeExpr(b, kv, u.Key())
		g.sizeExpr(b, vv, u.Elem())
		emitf(b, "\t}\n")
	case *types.Struct:
		// Named struct: delegate to its generated Size().
		emitf(b, "\ts += (&%s).Size()\n", ref)
	case *types.Interface:
		// Tagged union: tag varint + the active member's own Size, or just the
		// nil tag (one byte) when the interface is nil.
		members, _ := g.unionMembersOf(t)
		emitf(b, "\tswitch v := %s.(type) {\n", ref)

		for idx, m := range members {
			emitf(b, "\tcase *%s:\n\t\ts += %d + v.Size()\n", types.TypeString(m, relativeTo(g)), uvarintLen(uint64(idx+1)))
		}

		emitf(b, "\tcase nil:\n\t\ts += %d\n", uvarintLen(0))
		emitf(b, "\tdefault:\n\t\tpanic(%q)\n\t}\n", unionPanic(g, t))
	}
}

// emitMarshal writes the Marshal method for t, encoding fields in order.
func (g *generator) emitMarshal(b *bytes.Buffer, t *types.Named, fs []field) {
	recv := t.Obj().Name()
	q := g.codecQual

	emitf(b, "// Marshal encodes the receiver into b, which must be at least Size() bytes,\n")
	emitf(b, "// and returns the number of bytes written.\n")
	emitf(b, "func (r *%s) Marshal(b []byte) int {\n\ti := 0\n", recv)

	for _, f := range fs {
		g.marshalExpr(b, "r."+f.name, f.typ)
	}

	emitf(b, "\t_ = %s.PutU64\n\treturn i\n}\n\n", q)
}

// marshalExpr writes code that encodes the value ref of type t at offset i.
func (g *generator) marshalExpr(b *bytes.Buffer, ref string, t types.Type) {
	q := g.codecQual

	if isTime(t) {
		g.usedTime = true
		emitf(b, "\t%s.PutU64(b[i:], uint64(%s.UnixNano()))\n\ti += 8\n", q, ref)
		return
	}

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool:
			emitf(b, "\tif %s {\n\t\tb[i] = 1\n\t} else {\n\t\tb[i] = 0\n\t}\n\ti++\n", ref)
		case types.Uint8, types.Int8:
			emitf(b, "\tb[i] = byte(%s)\n\ti++\n", ref)
		case types.Uint16, types.Int16:
			emitf(b, "\t%s.PutU16(b[i:], uint16(%s))\n\ti += 2\n", q, ref)
		case types.Uint32, types.Int32:
			emitf(b, "\t%s.PutU32(b[i:], uint32(%s))\n\ti += 4\n", q, ref)
		case types.Float32:
			emitf(b, "\t%s.PutU32(b[i:], %s.F32bits(%s))\n\ti += 4\n", q, q, ref)
		case types.Uint64, types.Uint, types.Int64, types.Int:
			emitf(b, "\t%s.PutU64(b[i:], uint64(%s))\n\ti += 8\n", q, ref)
		case types.Float64:
			emitf(b, "\t%s.PutU64(b[i:], %s.F64bits(%s))\n\ti += 8\n", q, q, ref)
		case types.String:
			emitf(b, "\ti += %s.PutUvarint(b[i:], uint64(len(%s)))\n", q, ref)
			emitf(b, "\ti += copy(b[i:], %s.S2B(%s))\n", q, ref)
		}
	case *types.Slice:
		emitf(b, "\ti += %s.PutUvarint(b[i:], uint64(len(%s)))\n", q, ref)

		if isBytes(u) {
			emitf(b, "\ti += copy(b[i:], %s)\n", ref)
			return
		}

		iv := freshVar()
		emitf(b, "\tfor _, %s := range %s {\n", iv, ref)
		g.marshalExpr(b, iv, u.Elem())
		emitf(b, "\t}\n")
	case *types.Array:
		// No length prefix; []byte-style bulk copy for byte arrays.
		if isByteArray(u) {
			emitf(b, "\ti += copy(b[i:], %s[:])\n", ref)
			return
		}

		iv := freshIdx()
		emitf(b, "\tfor %s := 0; %s < %d; %s++ {\n", iv, iv, u.Len(), iv)
		g.marshalExpr(b, fmt.Sprintf("%s[%s]", ref, iv), u.Elem())
		emitf(b, "\t}\n")
	case *types.Pointer:
		emitf(b, "\tif %s != nil {\n\t\tb[i] = 1\n\t\ti++\n", ref)
		g.marshalExpr(b, "(*"+ref+")", u.Elem())
		emitf(b, "\t} else {\n\t\tb[i] = 0\n\t\ti++\n\t}\n")
	case *types.Map:
		emitf(b, "\ti += %s.PutUvarint(b[i:], uint64(len(%s)))\n", q, ref)
		kv, vv := freshVar(), freshVar()
		emitf(b, "\tfor %s, %s := range %s {\n", kv, vv, ref)
		g.marshalExpr(b, kv, u.Key())
		g.marshalExpr(b, vv, u.Elem())
		emitf(b, "\t}\n")
	case *types.Struct:
		emitf(b, "\ti += (&%s).Marshal(b[i:])\n", ref)
	case *types.Interface:
		// Tagged union: write the member's 1-based tag (0 for nil) then delegate
		// to the active member's Marshal.
		members, _ := g.unionMembersOf(t)
		emitf(b, "\tswitch v := %s.(type) {\n", ref)

		for idx, m := range members {
			emitf(b, "\tcase *%s:\n\t\ti += %s.PutUvarint(b[i:], %d)\n\t\ti += v.Marshal(b[i:])\n", types.TypeString(m, relativeTo(g)), q, idx+1)
		}

		emitf(b, "\tcase nil:\n\t\ti += %s.PutUvarint(b[i:], 0)\n", q)
		emitf(b, "\tdefault:\n\t\tpanic(%q)\n\t}\n", unionPanic(g, t))
	}
}

// emitUnmarshal writes the Unmarshal method for t, decoding fields in order. In
// safe mode the body is bounds-checked; otherwise it trusts the input.
func (g *generator) emitUnmarshal(b *bytes.Buffer, t *types.Named, fs []field) {
	recv := t.Obj().Name()
	q := g.codecQual

	emitf(b, "// Unmarshal decodes the receiver from b and returns the number of bytes consumed.\n")

	if g.safe {
		emitf(b, "// It returns %s.ErrShortBuffer if b is truncated (safe mode).\n", q)
	} else {
		emitf(b, "// The returned error is always nil; truncated input may panic (fast mode).\n")
	}

	emitf(b, "func (r *%s) Unmarshal(b []byte) (int, error) {\n\ti := 0\n\tvar nn uint64\n\tvar cc int\n\t_ = nn\n\t_ = cc\n", recv)

	for _, f := range fs {
		g.unmarshalExpr(b, "r."+f.name, f.typ)
	}

	emitf(b, "\t_ = %s.U64\n\treturn i, nil\n}\n\n", q)
}

// unmarshalExpr writes code that decodes the value ref of type t at offset i.
func (g *generator) unmarshalExpr(b *bytes.Buffer, ref string, t types.Type) {
	q := g.codecQual

	if isTime(t) {
		g.usedTime = true
		g.guardN(b, 8)
		// Reconstruct from unix-nanoseconds, normalized to UTC (monotonic clock
		// and original location are not preserved — the documented trade).
		emitf(b, "\t%s = time.Unix(0, int64(%s.U64(b[i:]))).UTC()\n\ti += 8\n", ref, q)
		return
	}

	tn := types.TypeString(t, relativeTo(g))

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool:
			g.guardN(b, 1)
			emitf(b, "\t%s = b[i] != 0\n\ti++\n", ref)
		case types.Uint8, types.Int8:
			g.guardN(b, 1)
			emitf(b, "\t%s = %s(b[i])\n\ti++\n", ref, tn)
		case types.Uint16, types.Int16:
			g.guardN(b, 2)
			emitf(b, "\t%s = %s(%s.U16(b[i:]))\n\ti += 2\n", ref, tn, q)
		case types.Uint32, types.Int32:
			g.guardN(b, 4)
			emitf(b, "\t%s = %s(%s.U32(b[i:]))\n\ti += 4\n", ref, tn, q)
		case types.Float32:
			g.guardN(b, 4)
			emitf(b, "\t%s = %s.Bitsf32(%s.U32(b[i:]))\n\ti += 4\n", ref, q, q)
		case types.Uint64, types.Uint, types.Int64, types.Int:
			g.guardN(b, 8)
			emitf(b, "\t%s = %s(%s.U64(b[i:]))\n\ti += 8\n", ref, tn, q)
		case types.Float64:
			g.guardN(b, 8)
			emitf(b, "\t%s = %s.Bitsf64(%s.U64(b[i:]))\n\ti += 8\n", ref, q, q)
		case types.String:
			g.emitVarint(b)
			g.guardLen(b)
			if g.safe {
				// Portable mode: own the bytes (copy) so the result doesn't alias
				// the input buffer.
				emitf(b, "\t%s = string(b[i : i+int(nn)])\n\ti += int(nn)\n", ref)
			} else {
				emitf(b, "\t%s = %s.B2S(b[i : i+int(nn)])\n\ti += int(nn)\n", ref, q)
			}
		}
	case *types.Slice:
		if isBytes(u) {
			g.emitVarint(b)
			emitf(b, "\tif nn == 0 {\n\t\t%s = nil\n\t} else {\n", ref)
			g.guardLen(b)
			if g.safe {
				// Portable mode: copy into an owned slice (reusing capacity) so the
				// result doesn't alias the input buffer.
				emitf(b, "\t\t%s = append(%s[:0], b[i:i+int(nn)]...)\n\t\ti += int(nn)\n\t}\n", ref, ref)
			} else {
				emitf(b, "\t\t%s = b[i : i+int(nn)]\n\t\ti += int(nn)\n\t}\n", ref)
			}

			return
		}

		g.emitVarint(b)
		emitf(b, "\tif nn == 0 {\n\t\t%s = nil\n\t} else {\n", ref)
		g.guardLen(b) // each element is >= 1 byte, so nn > remaining ⇒ truncated; also caps make
		// Reuse the destination's backing array when it already has the capacity,
		// so repeated decodes into the same value stay allocation-free.
		emitf(b, "\tif cap(%s) >= int(nn) {\n\t\t%s = %s[:nn]\n\t} else {\n\t\t%s = make(%s, nn)\n\t}\n", ref, ref, ref, ref, tn)
		iv := freshIdx()
		emitf(b, "\tfor %s := range %s {\n", iv, ref)
		g.unmarshalExpr(b, fmt.Sprintf("%s[%s]", ref, iv), u.Elem())
		emitf(b, "\t}\n")
		emitf(b, "\t}\n")
	case *types.Array:
		// No length prefix; bulk-copy byte arrays, element-loop otherwise.
		if isByteArray(u) {
			g.guardN(b, int(u.Len()))
			emitf(b, "\tcopy(%s[:], b[i:i+%d])\n\ti += %d\n", ref, u.Len(), u.Len())
			return
		}

		iv := freshIdx()
		emitf(b, "\tfor %s := 0; %s < %d; %s++ {\n", iv, iv, u.Len(), iv)
		g.unmarshalExpr(b, fmt.Sprintf("%s[%s]", ref, iv), u.Elem())
		emitf(b, "\t}\n")
	case *types.Pointer:
		elemTn := types.TypeString(u.Elem(), relativeTo(g))
		g.guardN(b, 1) // nil flag
		emitf(b, "\tif b[i] != 0 {\n\t\ti++\n")
		tmp := freshIdx()
		emitf(b, "\t\tvar %s %s\n", tmp, elemTn)
		g.unmarshalExpr(b, tmp, u.Elem())
		emitf(b, "\t\t%s = &%s\n", ref, tmp)
		emitf(b, "\t} else {\n\t\ti++\n\t\t%s = nil\n\t}\n", ref)
	case *types.Map:
		keyTn := types.TypeString(u.Key(), relativeTo(g))
		valTn := types.TypeString(u.Elem(), relativeTo(g))
		g.emitVarint(b)
		cnt := freshIdx()
		emitf(b, "\tif nn == 0 {\n\t\t%s = nil\n\t} else {\n", ref)
		g.guardLen(b) // each entry is >= 1 byte, so nn > remaining ⇒ truncated; also caps make
		emitf(b, "\t%s := nn\n", cnt)
		// Reuse a non-nil destination map (clear keeps its buckets) so repeated
		// decodes into the same value skip the map-header allocation.
		emitf(b, "\tif %s != nil {\n\t\tclear(%s)\n\t} else {\n\t\t%s = make(%s, %s)\n\t}\n", ref, ref, ref, tn, cnt)
		iv := freshIdx()
		kt, vt := freshIdx(), freshIdx()
		emitf(b, "\tfor %s := uint64(0); %s < %s; %s++ {\n", iv, iv, cnt, iv)
		emitf(b, "\t\tvar %s %s\n\t\tvar %s %s\n", kt, keyTn, vt, valTn)
		g.unmarshalExpr(b, kt, u.Key())
		g.unmarshalExpr(b, vt, u.Elem())
		emitf(b, "\t\t%s[%s] = %s\n\t}\n", ref, kt, vt)
		emitf(b, "\t}\n")
	case *types.Struct:
		if g.safe {
			// Delegate to the nested type's safe Unmarshal and propagate its error.
			emitf(b, "\t{\n\t\tnnn, err := (&%s).Unmarshal(b[i:])\n\t\tif err != nil {\n\t\t\treturn i, err\n\t\t}\n\t\ti += nnn\n\t}\n", ref)
		} else {
			emitf(b, "\t{\n\t\tnnn, _ := (&%s).Unmarshal(b[i:])\n\t\ti += nnn\n\t}\n", ref)
		}
	case *types.Interface:
		// Tagged union: read the tag, then decode the matching member (tag 0 is
		// nil). An unrecognized tag is a normal interop condition, so it returns
		// ErrUnknownUnionTag in both modes rather than panicking.
		members, _ := g.unionMembersOf(t)
		g.emitVarint(b) // tag into nn
		emitf(b, "\tswitch nn {\n")
		emitf(b, "\tcase 0:\n\t\t%s = nil\n", ref)

		for idx, m := range members {
			v := freshIdx()
			emitf(b, "\tcase %d:\n\t\tvar %s %s\n", idx+1, v, types.TypeString(m, relativeTo(g)))

			if g.safe {
				emitf(b, "\t\tnnn, err := (&%s).Unmarshal(b[i:])\n\t\tif err != nil {\n\t\t\treturn i, err\n\t\t}\n\t\ti += nnn\n", v)
			} else {
				emitf(b, "\t\tnnn, _ := (&%s).Unmarshal(b[i:])\n\t\ti += nnn\n", v)
			}

			emitf(b, "\t\t%s = &%s\n", ref, v)
		}

		emitf(b, "\tdefault:\n\t\treturn i, %s.ErrUnknownUnionTag\n\t}\n", q)
	}
}

// guardN emits a length check before a fixed-width read of n bytes. It is a
// no-op unless safe mode is enabled.
func (g *generator) guardN(b *bytes.Buffer, n int) {
	if !g.safe {
		return
	}

	emitf(b, "\tif len(b)-i < %d {\n\t\treturn i, %s.ErrShortBuffer\n\t}\n", n, g.codecQual)
}

// guardLen emits a check that the remaining input can hold a length-prefixed
// payload of nn bytes. The comparison is done in uint64 so it stays correct for
// adversarially large nn (where int(nn) could wrap negative). It is a no-op
// unless safe mode is enabled.
func (g *generator) guardLen(b *bytes.Buffer) {
	if !g.safe {
		return
	}

	emitf(b, "\tif uint64(len(b)-i) < nn {\n\t\treturn i, %s.ErrShortBuffer\n\t}\n", g.codecQual)
}

// emitVarint emits the shared "decode a varint length into nn" snippet. In safe
// mode it rejects truncated (cc == 0) and overflowing (cc < 0) varints.
func (g *generator) emitVarint(b *bytes.Buffer) {
	q := g.codecQual

	emitf(b, "\tnn, cc = %s.Uvarint(b[i:])\n", q)

	if g.safe {
		emitf(b, "\tif cc <= 0 {\n\t\treturn i, %s.ErrShortBuffer\n\t}\n", q)
	}

	emitf(b, "\ti += cc\n")
}

// relativeTo returns a types.Qualifier that leaves target-package names
// unqualified and qualifies external packages (e.g. emits "time.Time").
func relativeTo(g *generator) types.Qualifier {
	return func(p *types.Package) string {
		if p == g.pkg {
			return "" // target package: emit unqualified names
		}

		return p.Name() // external package (e.g. "time"): qualify
	}
}

// isTime reports whether t is the standard library's time.Time.
func isTime(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}

	obj := named.Obj()

	return obj.Pkg() != nil && obj.Pkg().Path() == "time" && obj.Name() == "Time"
}

// isBytes reports whether s has a literal byte/uint8 element, so the raw copy
// fast path is type-correct. A named element type (e.g. []MyByte) is excluded:
// a []byte slice expression is not assignable to it and copy would reject the
// element-type mismatch, so it falls through to the element-wise path instead.
func isBytes(s *types.Slice) bool {
	b, ok := s.Elem().(*types.Basic)

	return ok && b.Kind() == types.Uint8
}

// isByteArray reports whether a has a literal byte/uint8 element. As with
// isBytes, a named element type is excluded so the bulk copy stays type-correct.
func isByteArray(a *types.Array) bool {
	b, ok := a.Elem().(*types.Basic)

	return ok && b.Kind() == types.Uint8
}

// fixedSize returns the constant encoded size of t in bytes and true when t has
// one: a fixed-width basic, time.Time, or an array (possibly nested) of those.
// It returns (0, false) for variable-length types.
func fixedSize(t types.Type) (int, bool) {
	if isTime(t) {
		return 8, true // int64 unix-nanoseconds
	}

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool, types.Uint8, types.Int8:
			return 1, true
		case types.Uint16, types.Int16:
			return 2, true
		case types.Uint32, types.Int32, types.Float32:
			return 4, true
		case types.Uint64, types.Int64, types.Uint, types.Int, types.Float64:
			return 8, true
		}
	case *types.Array:
		if esz, ok := fixedSize(u.Elem()); ok {
			return int(u.Len()) * esz, true
		}
	}

	return 0, false
}

// uvarintLen returns the number of bytes PutUvarint uses to encode x. It lets
// Size account for a union's constant tag width without a runtime call.
func uvarintLen(x uint64) int {
	n := 1

	for x >= 0x80 {
		x >>= 7
		n++
	}

	return n
}

// unionPanic builds the panic message emitted in a union's Marshal/Size default
// case, reached only when a value's dynamic type was never declared as a member.
func unionPanic(g *generator, iface types.Type) string {
	return fmt.Sprintf("goserde: value is not a registered member of union %s", types.TypeString(iface, relativeTo(g)))
}

// varCounter backs freshVar/freshIdx, giving every emitted temporary a name
// unique within a generation run.
var varCounter int

// freshVar returns a unique range-variable name (e1, e2, ...).
func freshVar() string { varCounter++; return fmt.Sprintf("e%d", varCounter) }

// freshIdx returns a unique loop/temporary name (j1, j2, ...).
func freshIdx() string { varCounter++; return fmt.Sprintf("j%d", varCounter) }

// isFixedWidth reports whether t occupies a fixed number of raw memory bytes
// that survive a same-arch memmove: a fixed-width basic, or an array (possibly
// nested) of them. time.Time is deliberately excluded — it is a struct encoded
// as UnixNano, not copied as raw memory. Strings, slices, pointers, maps, and
// named structs are not fixed-width.
func isFixedWidth(t types.Type) bool {
	if isTime(t) {
		return false
	}

	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool, types.Uint8, types.Int8, types.Uint16, types.Int16,
			types.Uint32, types.Int32, types.Float32,
			types.Uint64, types.Int64, types.Uint, types.Int, types.Float64:
			return true
		}
	case *types.Array:
		return isFixedWidth(u.Elem())
	}

	return false
}

// blittable reports whether every field is fixed-width (basics or arrays of
// them), so the whole struct can be copied as raw memory. Strings, slices,
// pointers, and maps disqualify it. This is the trusted-bytes, same-arch fast
// path that puts fixed structs in the ~sub-ns tier.
func (g *generator) blittable(fs []field) bool {
	if len(fs) == 0 {
		return false
	}

	for _, f := range fs {
		if !isFixedWidth(f.typ) {
			return false
		}
	}

	return true
}

// emitBlitSize writes the Size method for a blittable struct: its fixed
// in-memory size.
func (g *generator) emitBlitSize(b *bytes.Buffer, t *types.Named) {
	recv := t.Obj().Name()

	emitf(b, "// Size returns the fixed wire size of %s (blittable fast path).\n", recv)
	emitf(b, "func (r *%s) Size() int {\n\treturn int(unsafe.Sizeof(*r))\n}\n\n", recv)
}

// emitBlitMarshal writes the Marshal method for a blittable struct: a single
// raw-memory copy of the receiver into b.
func (g *generator) emitBlitMarshal(b *bytes.Buffer, t *types.Named) {
	recv := t.Obj().Name()

	emitf(b, "// Marshal copies %s as raw memory into b (trusted bytes, same arch).\n", recv)
	emitf(b, "func (r *%s) Marshal(b []byte) int {\n", recv)
	emitf(b, "\tn := int(unsafe.Sizeof(*r))\n")
	emitf(b, "\tcopy(b, unsafe.Slice((*byte)(unsafe.Pointer(r)), n))\n")
	emitf(b, "\treturn n\n}\n\n")
}

// emitBlitUnmarshal writes the Unmarshal method for a blittable struct: a single
// raw-memory copy of b back into the receiver, length-guarded in safe mode.
func (g *generator) emitBlitUnmarshal(b *bytes.Buffer, t *types.Named) {
	recv := t.Obj().Name()

	emitf(b, "// Unmarshal copies raw memory from b back into %s.\n", recv)
	emitf(b, "func (r *%s) Unmarshal(b []byte) (int, error) {\n", recv)
	emitf(b, "\tn := int(unsafe.Sizeof(*r))\n")

	if g.safe {
		emitf(b, "\tif len(b) < n {\n\t\treturn 0, %s.ErrShortBuffer\n\t}\n", g.codecQual)
	}

	emitf(b, "\tcopy(unsafe.Slice((*byte)(unsafe.Pointer(r)), n), b)\n")
	emitf(b, "\treturn n, nil\n}\n\n")
}
